### ISSUE TITLE
Support conditional writes

### ISSUE THREAD

**Issue by flokli** [liufuyang/bigtable_rs#65]
https://cloud.google.com/bigtable/docs/writing-data#conditional describes how to do conditional writes.

It would be nice if we'd be able to create these kinds of requests. In my specific usecase, I only want to perform an insert in case the key doesn't already exist.

**Comment by liufuyang** [comment]
I think it is already doable here as we expose all the raw RPC APIs to bigtable, perhaps you can give it a try. 

I think you can follow the example of https://github.com/liufuyang/bigtable_rs/blob/main/examples/src/sample_row_keys.rs

which calls onto the raw API [sample_row_keys](https://github.com/liufuyang/bigtable_rs/blob/bbe36065f2fe5aeaf4514df4293a44ce82544910/bigtable_rs/src/google/google.bigtable.v2.rs#L1822)

What you need to do is to replace that to call to [check_and_mutate_row](https://github.com/liufuyang/bigtable_rs/blob/bbe36065f2fe5aeaf4514df4293a44ce82544910/bigtable_rs/src/google/google.bigtable.v2.rs#L1890)
And setup a [CheckAndMutateRowRequest](https://github.com/liufuyang/bigtable_rs/blob/bbe36065f2fe5aeaf4514df4293a44ce82544910/bigtable_rs/src/google/google.bigtable.v2.rs#L1267) manually.

You should see the CheckAndMutateRowRequest match up very good with the golang examples you linked. 
The raw proto file is [here](https://github.com/googleapis/googleapis/blob/4bcefb91a6b7da272db7b4d045f12c6292964b20/google/bigtable/v2/bigtable.proto#L173) if you need more reference.

Or perhaps these docs can help as well:
* https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#google.bigtable.v2.CheckAndMutateRowRequest
* Here (search "rpc CheckAndMutateRow") https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#google.bigtable.v2.Bigtable

Let me know if this helps, and if you really need, I might be able to try draft a simple example.

**Comment by flokli** [comment]
Thanks for the pointers! I hope it's enough, I will take a look first :-)

**Comment by flokli** [comment]
In fact, this was quite simple. I opened https://github.com/liufuyang/bigtable_rs/pull/68 threading things through - PTAL.

**Comment by liufuyang** [comment]
Thanks a lot, indeed it was simple. I released 0.2.8, give it a try then :)

**Comment by flokli** [comment]
Yes, this worked. Thanks again!
