### ISSUE TITLE
Row merging missing edgecases

### ISSUE THREAD

**Issue by igorbernstein2** [liufuyang/bigtable_rs#7]
Hi,

Thanks for publishing this. I took a quick peek and noticed that the row merging logic is a bit off (it seems like you are merging values from different timestamps). Google published a test suite to check correctness of row merging:
https://github.com/googleapis/conformance-tests/blob/master/bigtable/v2/readrows.json

Here is an example of the java client using it:
https://github.com/googleapis/java-bigtable/blob/main/google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/readrows/ReadRowsMergingAcceptanceTest.java

and in c++:
https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/bigtable/internal/readrowsparser_acceptance_tests.inc

I'm pretty sure every google client language implementation has a test that uses it (in case you'd like an example in a different language)

**Comment by liufuyang** [comment]
Interesting, thanks for all the good info. I haven't been working on this repo for sometime, might need some time to look into this. Otherwise you are very welcome to provide a fix if you already see an easy solution there :)

**Comment by liufuyang** [comment]
Reopens as tests are not added yet.

**Comment by liufuyang** [comment]
@igorbernstein2 Hey Igor, thanks again for linking the test files. I have migrated the JSON tests from [the link](https://github.com/googleapis/conformance-tests/blob/master/bigtable/v2/readrows.json) you provided above in PR #13 

I will do a release of the package soon and feel free to let me know whether there are more places you think I can fix :)

**Comment by liufuyang** [comment]
As I have [0.1.7](https://crates.io/crates/bigtable_rs) released I will just close this issue now. But feel free to let me re-open it if some of you think there is more to do :)
